import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyContextProvider from "@/MyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weeraphat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MyContextProvider>
        <body className={inter.className}>{children}</body>
      </MyContextProvider>
    </html>
  );
}
