import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "layout",
  description: "Generated by create next app",
};
export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div>asdf</div>
      {children}
      <div>อะไรไม่รู้</div>
    </main>
  );
}
